import type { AuditSnapshot, DataRoomPreview } from "@/lib/types";
export const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
export async function getHealth() { const r = await fetch(`${API_URL}/api/health`, { cache: "no-store" }); if (!r.ok) throw new Error("Backend is unavailable"); return r.json(); }
export async function getDataRoomPreview(): Promise<DataRoomPreview> { const r = await fetch(`${API_URL}/api/data-room/preview`, { cache: "no-store" }); if (!r.ok) throw new Error("Could not load data room"); return r.json(); }
export async function createAudit(files: File[] = []) { const body = new FormData(); files.forEach((file) => body.append("files", file)); const r = await fetch(`${API_URL}/api/audits`, { method: "POST", body }); if (!r.ok) { const payload = await r.json().catch(() => ({})); throw new Error(payload.detail || "Could not create audit"); } return r.json() as Promise<{ audit_id: string; status: string; events_url: string }>; }
export async function getAudit(id: string): Promise<AuditSnapshot> { const r = await fetch(`${API_URL}/api/audits/${id}`, { cache: "no-store" }); if (!r.ok) throw new Error("Audit not found"); return r.json(); }
export async function decideTask(auditId: string, taskId: string, decision: "approve" | "hold" | "reject", note = "") { const r = await fetch(`${API_URL}/api/audits/${auditId}/tasks/${taskId}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, note }) }); if (!r.ok) { const payload = await r.json().catch(() => ({})); throw new Error(payload.detail || "Could not process decision"); } return r.json(); }
export async function syncTaskVerification(auditId: string, taskId: string) { const r = await fetch(`${API_URL}/api/audits/${auditId}/tasks/${taskId}/sync-verification`, { method: "POST" }); if (!r.ok) { const payload = await r.json().catch(() => ({})); throw new Error(payload.detail || "Could not check Slack verification"); } return r.json(); }
export function money(value: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
