export type Integration = { name: string; state: "connected" | "degraded" | "unavailable"; detail: string };
export type AuditEvent = { step: string; status: "started" | "progress" | "completed" | "warning" | "failed"; message: string; timestamp: string; duration_ms: number; payload?: { activity?: ResearchActivity } & Record<string, unknown> };
export type Scores = { confidence: number; action_safety: number; evidence_completeness: number; expected_roi: number; hallucination_risk: number; citation_coverage: number };
export type Strategy = { id: string; vendor: string; title: string; description: string; savings: number; risk: string; scores: Scores; approved: boolean; gate_result: "execute" | "human_review" };
export type TraceNode = { id: string; label: string; status: "pending" | "running" | "completed" | "warning"; duration_ms: number; children: TraceNode[] };
export type UploadedDocument = { id: string; name: string; document_type: string; size_bytes: number; row_count: number; status: "parsed" | "fixture" | "unsupported"; summary: string; evidence_count: number };
export type EvidenceRecord = { id: string; document_id: string; vendor: string; claim: string; locator: string; value: string; confidence: number };
export type DatasetSummary = { documents: number; records: number; vendors: number; employees: number; contracts: number; invoices: number; capabilities: number; period: string; coverage: number };
export type ResearchActivity = { id: string; kind: "search" | "navigate" | "inspect" | "extract" | "compare" | "cite"; status: "running" | "completed" | "cached"; label: string; detail: string; vendor: string; query: string; url: string; timestamp: string };
export type ResearchFinding = { vendor: string; competitor: string; benchmark_price: number; source_url: string; source_status: "live" | "cached"; finding: string; category: string; search_query: string; page_title: string; evidence_excerpt: string; scraped_at: string };
export type TaskVerification = { status: "awaiting_reply" | "confirmed_reclaim" | "confirmed_keep" | "unrecognized" | "error"; channel_id: string; thread_ts?: string; posted_receipt_id?: string; prompt: string; response_text: string; interpretation?: "reclaim" | "keep"; posted_at?: string; checked_at?: string; responded_at?: string; error_detail: string };
export type VerificationEvent = { id: string; task_id: string; vendor: string; resource: string; status: string; response_text: string; interpretation?: "reclaim" | "keep"; thread_ts?: string; occurred_at: string };
export type RecoveryTask = { id: string; strategy_id: string; vendor: string; title: string; action: string; savings: number; owner: string; urgency: "now" | "this_week" | "before_renewal"; status: "awaiting_verification" | "pending_approval" | "approved" | "held" | "rejected" | "executed" | "failed" | "closed_no_action"; recommendation: "approve" | "review" | "hold"; gate_confidence: number; gate_action_safety: number; rationale: string; evidence_refs: string[]; draft_to: string; draft_subject: string; draft_body: string; decision_note: string; decided_at?: string; receipts: string[]; verification?: TaskVerification };
export type AuditSnapshot = {
  audit_id: string; company: string; status: "queued" | "running" | "completed" | "failed"; started_at: string; completed_at?: string;
  integrations: Integration[];
  metrics: { potential_leakage: number; verified_recoverable: number; redundancy_savings: number; negotiation_leverage: number; action_priority: string };
  uploaded_documents: UploadedDocument[]; evidence: EvidenceRecord[]; dataset_summary: DatasetSummary;
  spend: Array<{ vendor: string; annual_spend: number; active_seats?: number; purchased_seats?: number; status: string }>;
  leaks: Array<{ id: string; vendor: string; leak_type: string; annual_loss: number; severity: string; evidence: string }>;
  redundancy: Array<{ tool_a: string; tool_b: string; overlap_score: number; annual_redundant_spend: number; rationale: string }>;
  employee_replies: Array<{ employee: string; vendor: string; resource: string; days_active_90d: number; manager: string; reply: string; response: string; interpretation: string; recoverable: number }>;
  verification_events: VerificationEvent[];
  research: ResearchFinding[]; research_activity: ResearchActivity[];
  strategies: Strategy[];
  recovery_tasks: RecoveryTask[];
  actions: Array<{ id: string; kind: string; title: string; status: string; tool: string; resource_id?: string; detail: string; payload?: Record<string, unknown> }>;
  trace_tree?: TraceNode; trace_id?: string; trace_url?: string;
  analytics: { source: "clickhouse" | "fixture"; row_count: number; freshness: string; spend_by_vendor: Array<{ vendor: string; spend: number }>; leakage_by_category: Array<{ category: string; value: number }>; recovery_pipeline: Array<{ stage: string; value: number }>; table_counts: Array<{ table: string; rows: number }>; query_log: Array<{ name: string; purpose: string; sql: string }> };
  report_markdown: string;
};
export type DataRoomPreview = { documents: UploadedDocument[]; evidence: EvidenceRecord[]; summary: DatasetSummary; required_files: string[] };
